"""
First-Week Adoption Checklist Generator
Creates PDF checklist for new pet parents
"""

from fpdf import FPDF
from datetime import datetime
import os


class AdoptionChecklistPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'First Week Adoption Checklist', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Your guide to a successful start with your new pet', 0, 1, 'C')
        self.ln(5)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by FurFindr - {datetime.now().strftime("%B %d, %Y")}', 0, 0, 'C')


def generate_checklist_pdf(pet_name="Your New Pet", pet_type="Dog", output_path="adoption_checklist.pdf"):
    """
    Generate a comprehensive first-week adoption checklist PDF
    
    Args:
        pet_name: Name of the adopted pet
        pet_type: Type of pet (Dog, Cat, etc.)
        output_path: Where to save the PDF
    
    Returns:
        Path to generated PDF
    """
    
    pdf = AdoptionChecklistPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Introduction
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, f'Welcome {pet_name} Home!', 0, 1)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 5, 
        'The first week is critical for building trust and establishing routines. '
        'Use this checklist to ensure a smooth transition and set your pet up for success.'
    )
    pdf.ln(5)
    
    # Day 1
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(200, 220, 255)
    pdf.cell(0, 8, 'Day 1: Arrival & Settling In', 0, 1, 'L', True)
    pdf.set_font('Arial', '', 10)
    
    day1_items = [
        '[ ] Set up safe space with bed, water, food bowls',
        '[ ] Show pet location of food, water, bathroom area',
        '[ ] Keep environment calm - limit visitors',
        '[ ] Begin using pet\'s name positively',
        '[ ] Take initial photos for records',
        f'[ ] Schedule vet appointment within 7 days',
        '[ ] Give space - allow pet to explore at own pace'
    ]
    
    for item in day1_items:
        pdf.cell(0, 6, item, 0, 1)
    pdf.ln(3)
    
    # Days 2-3
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(200, 220, 255)
    pdf.cell(0, 8, 'Days 2-3: Building Routine', 0, 1, 'L', True)
    pdf.set_font('Arial', '', 10)
    
    day23_items = [
        '[ ] Establish feeding schedule (same times daily)',
        '[ ] Start regular potty breaks/litter box checks',
        '[ ] Begin short play sessions',
        '[ ] Practice basic commands with treats (sit, come)',
        '[ ] Introduce to immediate household members only',
        '[ ] Monitor eating, drinking, elimination habits',
        '[ ] Start crate training if applicable'
    ]
    
    for item in day23_items:
        pdf.cell(0, 6, item, 0, 1)
    pdf.ln(3)
    
    # Days 4-5
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(200, 220, 255)
    pdf.cell(0, 8, 'Days 4-5: Expanding Comfort Zone', 0, 1, 'L', True)
    pdf.set_font('Arial', '', 10)
    
    day45_items = [
        f'[ ] Increase exercise/play gradually (if {pet_type.lower()})',
        '[ ] Introduce grooming basics (brushing, nail check)',
        '[ ] Practice leash walking indoors (dogs)',
        '[ ] Reward good behavior consistently',
        '[ ] Address any concerns with vet or trainer',
        '[ ] Take note of favorite toys/activities',
        '[ ] Begin alone-time training (short periods)'
    ]
    
    for item in day45_items:
        pdf.cell(0, 6, item, 0, 1)
    pdf.ln(3)
    
    # Days 6-7
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(200, 220, 255)
    pdf.cell(0, 8, 'Days 6-7: Building Confidence', 0, 1, 'L', True)
    pdf.set_font('Arial', '', 10)
    
    day67_items = [
        '[ ] Short neighborhood walks (dogs) or window time (cats)',
        '[ ] Introduce puzzle toys for mental stimulation',
        '[ ] Photograph pet in happy moments',
        '[ ] Research training classes in your area',
        '[ ] Establish boundaries (furniture rules, etc.)',
        '[ ] Celebrate small wins!',
        '[ ] Reflect on progress and adjust routine as needed'
    ]
    
    for item in day67_items:
        pdf.cell(0, 6, item, 0, 1)
    pdf.ln(5)
    
    # Red Flags
    pdf.add_page()
    pdf.set_font('Arial', 'B', 14)
    pdf.set_fill_color(255, 200, 200)
    pdf.cell(0, 10, 'When to Call Your Vet', 0, 1, 'L', True)
    pdf.set_font('Arial', '', 10)
    
    red_flags = [
        '- Not eating or drinking for 24+ hours',
        '- Vomiting or diarrhea (especially if repeated)',
        '- Lethargy or hiding constantly',
        '- Difficulty breathing',
        '- Limping or signs of pain',
        '- Aggression that worsens',
        '- Any behavior that concerns you'
    ]
    
    for flag in red_flags:
        pdf.cell(0, 6, flag, 0, 1)
    
    pdf.ln(5)
    pdf.set_font('Arial', 'I', 10)
    pdf.multi_cell(0, 5, 
        'Remember: Every pet adjusts at their own pace. Some settle in within days, '
        'others may take weeks. Be patient, consistent, and celebrate progress!'
    )
    
    # Resources
    pdf.ln(5)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 8, 'Helpful Resources', 0, 1)
    pdf.set_font('Arial', '', 10)
    
    resources = [
        'Training: ASPCA Virtual Pet Behaviorist (aspcapro.org)',
        'Veterinary Q&A: AskVet or Vetster (telehealth)',
        'Behavior Help: Certified Applied Animal Behaviorists (CAAB)',
        'Community: Local pet parent Facebook groups'
    ]
    
    for resource in resources:
        pdf.cell(0, 6, f'- {resource}', 0, 1)
    
    # Save
    os.makedirs('output', exist_ok=True)
    full_path = os.path.join('output', output_path)
    pdf.output(full_path)
    
    return full_path


if __name__ == "__main__":
    # Test PDF generation
    pdf_path = generate_checklist_pdf(
        pet_name="Max",
        pet_type="Dog"
    )
    print(f"✅ Checklist generated: {pdf_path}")
