name: Send Email Alerts

on:
  schedule:
    # Run at 7 AM UTC daily (after ETL completes)
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  send-alerts:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt
      
      - name: Send email digests
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: python etl/email_digest.py
